version: 2

jobs:
  build:
    working_directory: ~/channel
    docker:
      - image: rust:1.21
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update && apt-get install -y libgstreamer1.0-dev libgtk-3-dev
      - run:
          name: Install dependencies
          command: cargo install
      - run:
          name: Run tests
          command: cargo test
